# Generated by Django 3.0.5 on 2020-04-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=30)),
                ('datetime_creation', models.DateTimeField()),
                ('datetime_expiration', models.DateTimeField()),
                ('datetime_deletion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXPIRED', 'Expired'), ('OUTZONE', 'Outzone'), ('DELETE_CANDIDATE', 'Delete candidate')], max_length=20)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainslist.Domain')),
            ],
        ),
    ]
