version: '3'

services:
  postgres:
    image: docker.io/library/postgres:alpine
    environment:
      # this allows passwordless login
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
    - 127.0.0.1:54321:5432